approve_by_comment: false
approve_regex: ^Approved
reject_regex: ^Rejected
reset_on_push: false
reviewers:
  members:
  - davegaeddert
  - pullapprover
  - davegaedderttest
  - joelgaeddert
  name: default
  required: 1
