# extends: default
approve_by_comment: yes
approve_regex: '^(Approved|:\+1:)'
reject_regex: ^Rejected
reset_on_reopened: true
reset_on_push: true
reject_value: 0
author_approval: required
always_pending:
    title_regex: '^(WIP|wip)'
    labels:
        - wip
reviewers:
    -
        name: legal
        required: 1
        members:
          - davegaeddert
    -
        name: by_team
        required: 1
        teams:
            - testers
