approve_by_comment: yes
reject_regex: ^Rejected
reviewers:
  -
    name: normal
    required: -1
    members:
      - davegaedderttest
      - pullapprover
  -
    name: buggers
    required: 1
    members:
      - davegaeddert
    conditions:
      labels: 
        - bug
        - question
      files:
        - **/*.md
        - LICENSE
