approve_by_comment: yes
reject_regex: ^Rejected
reviewers:
  -
    name: normal
    required: -1
    members:
      - davegaeddert
      - pullapprover
  -
    name: buggers
    required: 1
    members:
      - davegaeddert
    conditions:
      labels: bug
