approve_by_comment: yes
approve_regex: ^(Approved|:\+1:|\\U0001f44d)
reject_regex: ^Rejected
reset_on_reopened: true
reset_on_push: true
reject_value: 0
author_approval: required
reviewers:
  -
    name: normal
    required: 2
    members:
      - davegaedderttest
      - Pullapprover
  -
    name: legal
    required: 1
    members:
      - davegaeddert
    conditions:
      files:
        - LICENSE
