approve_by_comment: true
approve_regex: ^Approved
reject_regex: ^Rejected
reset_on_push: true
reset_on_reopened: true
author_approval: default
reviewers:
  members:
  - davegaeddert
  name: default
  required: 1
