approve_by_comment: true
reviewers:
  -
    name: test
    required: 2
    members:
      - davegaeddert
      - "@pullapprover"
  -
    name: just-dave
    required: 1
    members:
      - davegaeddert
