# extends: default
approve_by_comment: yes
approve_regex: '^(Approved|:\+1:)'
reject_regex: ^Rejected
reset_on_reopened: true
reset_on_push: no
#reject_value: -1
author_approval: required
always_pending:
    title_regex: '^(WIP|wip)'
    labels:
        - wip
always_rejected:
    title_regex: 'DISALLOW'
    labels:
        - bug
    explanation: 'Rejected dude...'
signed_off_by:
    required: true
reviewers:
    -
        name: legal
        required: 1
        members:
          - davegaeddert
        approve_by_comment:
            enabled: true
            approve_regex: '^Legal+'
    -
        name: labels
        required: 1
        members:
            - davegaeddert
        conditions:
            labels:
                - duplicate
    -
        name: by_team
        required: 1
        teams:
            - testers
    -
        name: feature-to-deploy
        required: 1
        members:
            - davegaeddert
        conditions:
            branches:
                - deploy...feature
