approve_by_comment: yes
reject_regex: ^Rejected
reset_on_reopened: true
reset_on_push: true
reject_value: -3
author_approval: required
reviewers:
  -
    required: 2
    members:
      - davegaeddert
      - davegaedderttest
      - pullapprover
