extends: base
approve_by_comment: yes
approve_regex: ^Yes
reject_regex: ^Rejected
reset_on_push: false
reviewers:
  -
    members: all
    name: default
    required: 1
  -
    members:
      - davegaeddert
      - pullapprover
    required: 2
    name: test
  
